### ISSUE TITLE
Building fails on macOS Ventura

### ISSUE THREAD

**Issue by Moneil97** [EatonGMBD/Builder#23]
Building code fails on macOS Ventura due to an old version of the `macos-release` package. This is being included from the `octokit/rest` package. We either need to manually update this package, or we might be able to merge in the changes from https://github.com/electricimp/Builder 

```
eatonem/em-device-firmware/ (master) > impt build generate -g $MDEV
Prebuild succeeded
Error: Unknown error: /usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/universal-user-agent/dist-node/index.js:17
    throw error;
    ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/macos-release/index.js:27:26)
    at osName (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/os-name/index.js:21:18)
    at getUserAgent (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/universal-user-agent/dist-node/index.js:11:53)
    at parseOptions (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/@octokit/rest/lib/parse-client-options.js:80:57)
    at new Octokit (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/@octokit/rest/lib/constructor.js:23:31)
    at Function.fetch (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/Builder/src/Readers/GithubReader.js:199:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/Builder/src/Readers/GithubReader.js:302:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
 (exit code 1) (/Users/e0619169/Documents/repos/eatonem/em-device-firmware/src/agent.nut:37)
IMPT COMMAND FAILS
```

**Comment by Moneil97** [comment]
The quick workaround is to manually update `/usr/local/lib/node_modules/imp-central-impt-eaton/node_modules/macos-release/index.js` to use the nameMap table from https://www.npmjs.com/package/macos-release?activeTab=code 

```
const nameMap = new Map([
	[23, ['Sonoma', '14']],
	[22, ['Ventura', '13']],
	[21, ['Monterey', '12']],
...
```
